version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "ca-central-1"
    IMAGE_REPO_NAME: fraud-detection-repo
    AWS_ACCOUNT_ID: 108271871935
    IMAGE_TAG: latest
    CLUSTER_NAME: WebServerCluster
    SERVICE_NAME: WebServerService

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "AWS ECR Login successfull at`date`"
      
  build:
    commands:
      - echo Build started on `date`
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Conyainer builded successfully at`date`"

  post_build:
    commands:
      - echo Pushing image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo "Image pushed successfully to ECR registry at `date`"
  deploy:
    commands:
      - echo Deploying to ECS cluster $CLUSTER_NAME...
      # Force ECS service to pick up the new image
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment
      - echo "Deployment to ECS cluster triggered at `date`"
